/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import { useState } from 'react'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import LayoutAuth from '@/containers/LayoutAuth/LayoutAuth'
import FormControl from '@/containers/FormControl/FormControl'

import {
  InputText,
  InputPassword,
  Button,
  InputEmail,
  H1,
  H2,
  Space,
} from '@/components'
import actionTypes from '@/configs/actionTypes'
import { useRouter } from 'next/router'
export default function Login() {
  const dispatch = useDispatch()
  const router = useRouter()
  const [formValue, setFormvalue] = useState({})
  const SubmitHandler = (event) => {
    event.preventDefault()
    console.log('form values', formValue)
    dispatch({
      type: actionTypes.LOGIN,
      logged: true,
      email: formValue.email,
    })
    router.push('/')
  }
  const ChangeHandle = (name, value) => {
    setFormvalue({
      ...formValue,
      [name]: value,
    })
  }
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <>
          <Space />
          <H2 align="center">لاگین</H2>
          <form
            css={css`
              width: 70%;
            `}
          >
            <FormControl>
              <InputEmail
                placeholder="email"
                changeHandle={(val) => ChangeHandle('email', val)}
              />
            </FormControl>
            <FormControl>
              <InputPassword
                placeholder="password"
                changeHandle={(val) => ChangeHandle('password', val)}
              />
            </FormControl>
            <FormControl>
              <Button submitHandler={SubmitHandler} type="large">
                ورود
              </Button>
            </FormControl>
          </form>
        </>
      </LayoutAuth>
    </>
  )
}
