/** @jsxImportSource @emotion/react */
import { jsx, css, Global, ClassNames } from '@emotion/react'
import Head from 'next/head'
import LayoutAuth from '@/containers/LayoutAuth/LayoutAuth'
import { InputText, InputPassword, Button } from '@/components'

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <form>
          <InputText placeholder="email" />
          <InputPassword placeholder="password" />
          <Button type="success">Sign in</Button>
        </form>
      </LayoutAuth>
    </>
  )
}
