/** @jsxImportSource @emotion/react */
import { jsx, css, Global, ClassNames } from '@emotion/react'
import Head from 'next/head'
import LayoutAuth from '@/containers/LayoutAuth/LayoutAuth'
import FormControl from '@/containers/FormControl/FormControl'
import {
  InputText,
  InputPassword,
  Button,
  InputEmail,
  H1,
  H2,
  Space,
} from '@/components'

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <>
          <Space />
          <H2 align="center">لاگین</H2>
          <form
            css={css`
              width: 70%;
            `}
          >
            <FormControl>
              <InputEmail placeholder="email" />
            </FormControl>
            <FormControl>
              <InputPassword placeholder="password" />
            </FormControl>
            <FormControl>
              <Button type="success">Sign in</Button>
            </FormControl>
          </form>
        </>
      </LayoutAuth>
    </>
  )
}
